// Generated by CoffeeScript 1.6.1
(function() {
  var Network,
    _this = this;

  $(window).load(function() {
    var net;
    return net = new Network();
  });

  Network = (function() {

    Network.prototype.gameObjects = [];

    function Network() {
      var canvas, socket,
        _this = this;
      this.spawn = function(data) {
        return Network.prototype.spawn.apply(_this, arguments);
      };
      canvas = document.getElementById("Canvas");
      alert(canvas);
      canvas.width = 1000;
      canvas.height = 1000;
      this.stage = new createjs.Stage(canvas);
      alert(this.stage);
      this.testshape = new createjs.Shape();
      this.testshape.graphics.beginFill("#951");
      this.testshape.graphics.drawRect(50, 50, 50, 50);
      this.stage.addChild(this.testshape);
      this.stage.update();
      createjs.Ticker.setFPS(20);
      createjs.Ticker.addEventListener("tick", function(ev) {
        return _this.stage.update();
      });
      socket = io.connect("http://secret-archer.lhk.c9.io");
      socket.on("NEWS", function(data) {
        return alert(data.news);
      });
      window.onmousedown = function(ev) {
        var mx, my;
        alert("click");
        mx = _this.stage.mouseX;
        my = _this.stage.mouseY;
        return _this.spawn({
          x: mx,
          y: my
        });
      };
    }

    Network.prototype.spawn = function(data) {
      var shape, x, y;
      x = data.x;
      y = data.y;
      shape = new createjs.Shape();
      shape.graphics.beginFill("#555");
      shape.graphics.drawRect(x - 25, y - 25, 50, 50);
      this.stage.addChild(shape);
      return this.stage.update();
    };

    return Network;

  })();

}).call(this);
